name: CI
on:
  pull_request:
    branches:
      - main

env:
  GCP_REGISTRY: null
  AWS_REGISTRY: null

jobs:
  project-ci:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry==1.6.1
        shell: bash

      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.9
          cache: poetry

      - name: Install Dev/Test Dependencies
        run: poetry install --with dev,test --all-extras

      - name: Run list
        run: pip list
  
  project-ci2:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry==1.6.1
        shell: bash

      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.9
          cache: poetry

      - name: Install Dev/Test Dependencies
        run: poetry install

      - name: Run list
        run: pip list
   ##########