name: fr826

on:
  workflow_dispatch:


jobs:
  build:
   
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: "3.11"
          architecture: "x86"
          cache: "poetry"
