name: issue1050

on: [workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Chocolatey
      run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
    - name: Install Python
      run: |
         choco install python --version=3.13
         python -m ensurepip
         python -m pip install --ignore-installed pip

    - name: Add Python to PATH
      run: |
         echo "Updating PATH manually"
         echo "${{ runner.tool_cache }}/Python/3.13.0/x64" >> $GITHUB_PATH

    - name: Set up Python
      uses: actions/setup-python@v5
      id: python
      with:
        python-version: '3.13'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'
        architecture: 'x64'
        update-environment: false

  
   
       
