name: run tests

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
   

    steps:
      - uses: actions/checkout@v4
        

      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          
