name: issue1050

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Python 3.13
      run: |
          # Download Python installer
          Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.13.0/python-3.13.0.exe -OutFile python-3.13.0.exe
          
          # Run the installer (install for all users, add to PATH, and install pip)
          Start-Process -Wait -FilePath .\python-3.13.0.exe -ArgumentList '/quiet', 'InstallAllUsers=1', 'PrependPath=1', 'Include_pip=1'
          
          # Clean up the installer
          Remove-Item -Force .\python-3.13.0.exe

    - name: Set up Python
      uses: gowridurgad/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'
        update-environment: false  # Do not update environment

