name: issue914-tolcache

on:
  workflow_dispatch:

jobs:
  test-python:
    name: Test Python pip install
    runs-on: self-hosted
   
    steps:
      - name: Github Actions Context Information
        uses: SiemaApplications-attic/vossloh-gh-actions/debug/show-github-context@v7
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Export CPATH
        run: export CPATH=$(pwd)/_work/_tool/Python/3.10.14/x64/include/python3.10
      - name: Python package install
        run: pip install PyGObject
