name: issue1050

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Python and pip
      run: |
        sudo apt-get update
        sudo apt-get install python3.13 python3-pip

    - name: Set up Python
      uses: gowridurgad/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'
        update-environment: false  # Do not update environment

