name: issue1050

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Python (if not already installed)
      shell: powershell
      run: |
        if (-not (Get-Command python -ErrorAction SilentlyContinue)) {
          Write-Host "Python not found, installing..."
          # Install Python (adjust the path and version as necessary)
          $pythonInstallerUrl = "https://www.python.org/ftp/python/3.13.0/python-3.13.0.exe"
          $installerPath = "$env:temp\python-installer.exe"
          Invoke-WebRequest -Uri $pythonInstallerUrl -OutFile $installerPath
          Start-Process -FilePath $installerPath -ArgumentList "/quiet", "InstallAllUsers=1", "PrependPath=1" -Wait
          Write-Host "Python installed"
        } else {
          Write-Host "Python already installed"
        }

    - name: Install pip
      shell: powershell
      run: |
        if (-not (Get-Command pip -ErrorAction SilentlyContinue)) {
          Write-Host "pip not found, installing..."
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip
          Write-Host "pip installed"
        } else {
          Write-Host "pip already installed"
        }

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'
        update-environment: false  # Do not update environment

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
