name: testing
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install poetry
      run: curl -sSL https://install.python-poetry.org | python3 -

    - uses: actions/setup-python@v5
      with:
         python-version: "3.12.3"
         cache: "poetry"

    - name: Install dependencies
      run: poetry install
