name: PR647

on:
  workflow_dispatch:


jobs:
  build:
   
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
     
      - name: Setup Python
        uses: gowridurgad/setup-python@testing-647pr
        with:
          python-version: '.python-version-file'
         
