name: PR647

on:
  workflow_dispatch:


jobs:
  build:
   
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
     
      - name: Setup Python
        uses: gowridurgad/setup-python@647pr-2
        with:
          python-version-file: 'python-version-file'
         
