name: pip-branchtesting

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: gowridurgad/setup-python@pip-version
      with:
        python-version: '3.11.11'
        pip-version: '23'
