name: python cache

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu_latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
