name: Node yarn cache

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: "macos-13"
            architecture: "arm64"
          - os: "macos-12"
            architecture: "x64"
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.target.os }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'poetry'
